### ISSUE TITLE
Poetry fails to find and install packages

### ISSUE THREAD

**Issue by banananeer** [astariul/github-hosted-pypi#69]
Hello! This is a really cool project and I would love to use it however I'm having some trouble getting it to work with poetry.

I created a default source in my pyproject file as the following
```
[[tool.poetry.source]]
name = "test"
url = "https://astariul.github.io/github-hosted-pypi/"
priority = "default"
```
and when I try to install public-hello I get the following error
```
poetry add public-hello

Could not find a matching version of package public-hello
```
Do you have any idea what may be going on?

**Comment by reinvantveer** [comment]
Hi @banananeer I was able to resolve the package using this pyprojec.toml:
```toml
[tool.poetry]
name = "github-hosted-pypi"
version = "0.1.0"
description = "A test for resolving packages using poetry to check on https://github.com/astariul/github-hosted-pypi/issues/69"
authors = ["reinvantveer <rein@vantveer.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "test"
url = "https://astariul.github.io/github-hosted-pypi/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```
adding public-hello results in:
```
$ poetry add public-hello
Using version ^0.0.0 for public-hello

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing public-hello (0.0.0)

Writing lock file
```
